# Generated by Django 3.1.4 on 2021-03-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210310_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong_lanmu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_lanmu', to='blog.lanmu'),
        ),
        migrations.AlterField(
            model_name='lanmu',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lanmu_children', to='blog.lanmu'),
        ),
    ]
