# Generated by Django 3.1.4 on 2021-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pinlun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinlun',
            name='text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
